version: '3'

services:
  ai-teacher-assistant:
    build: .
    ports:
      - "8080:80"
    volumes:
      # For development: mount these directories to see changes without rebuilding
      - ./js:/usr/share/nginx/html/js
      - ./css:/usr/share/nginx/html/css
      - ./index.html:/usr/share/nginx/html/index.html
